#!/usr/bin/env python3

import sys


def read_numbers_from_file(file_name):
    with open(file_name, "r") as file:
        lines = file.readlines()
    numbers = []
    for line in lines:
        numbers.append(int(line.strip()))
    return numbers


def find_factorization(n):
    for i in range(2, n):
        if n % i == 0:
            return f"{n}={i}*{n//i}"
    return None


def factorize_numbers(numbers):
    for n in numbers:
        factorization = find_factorization(n)
        if factorization:
            print(factorization)


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <file>")
        sys.exit(1)
    file_name = sys.argv[1]
    numbers = read_numbers_from_file(file_name)
    factorize_numbers(numbers)

