#!/usr/bin/env python3
"""Factor numbers in a file"""

import sys
import math


def read_numbers_from_file(file_name: str) -> list[int]:
    """Read numbers from a file and return them as a list of integers"""
    with open(file_name, "r", encoding="utf-8") as file:
        lines = file.readlines()
    numbers_to_factor = []
    for line in lines:
        numbers_to_factor.append(int(line))
    return numbers_to_factor


def find_factors(n: int) -> None:
    """Print the prime factors of the given integer n"""
    for i in range(2, int(math.sqrt(n))+1):
        while n % i == 0:
            print(f"{n}={i}*{n//i}")
            n //= i
    if n > 1:
        print(f"{n}={n}*1")


def factor_numbers_in_list(numbers: list[int]) -> None:
    """Factor each number in the given list"""
    for number in numbers:
        find_factors(number)


def main() -> None:
    """Parse the command line arguments and run the program"""
    if len(sys.argv) == 2:
        numbers = read_numbers_from_file(sys.argv[1])
        factor_numbers_in_list(numbers)
    else:
        print("Usage: python factor_numbers.py filename")


if __name__ == "__main__":
    main()

