#!/usr/bin/python3

import sys

def factorize(num):
    """
    Factorize a given number and return a list of tuples representing the
    factors.
    """
    factors = []
    if num % 2 == 0:
        factors.append((2, num // 2))
    else:
        for i in range(3, num, 2):
            if num % i == 0:
                factor = num // i
                for j in range(3, factor, 2):
                    if factor % j == 0 or i % j == 0:
                        break
                else:
                    factors.append((i, factor))
                    break
    return factors

if len(sys.argv) < 2:
    print("Usage: {} <file>".format(sys.argv[0]))
    sys.exit(1)

filename = sys.argv[1]

with open(filename, "r") as f:
    for line in f:
        num = int(line.strip())
        print("{}=".format(num), end="")
        factors = factorize(num)
        for factor in factors:
            print("{}*{}".format(factor[0], factor[1]), end="")
            if factor != factors[-1]:
                print(end=",")
        print()

